/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModesIndexRouteImport } from './routes/modes.index'
import { Route as ModesModeRouteImport } from './routes/modes.$mode'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesIndexRoute = ModesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModesRoute,
} as any)
const ModesModeRoute = ModesModeRouteImport.update({
  id: '/$mode',
  path: '/$mode',
  getParentRoute: () => ModesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/modes': typeof ModesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/modes/$mode': typeof ModesModeRoute
  '/modes/': typeof ModesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/modes/$mode': typeof ModesModeRoute
  '/modes': typeof ModesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/modes': typeof ModesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/modes/$mode': typeof ModesModeRoute
  '/modes/': typeof ModesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/modes'
    | '/sitemap.xml'
    | '/modes/$mode'
    | '/modes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/a-propos' | '/sitemap.xml' | '/modes/$mode' | '/modes'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/modes'
    | '/sitemap.xml'
    | '/modes/$mode'
    | '/modes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ModesRoute: typeof ModesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes/': {
      id: '/modes/'
      path: '/'
      fullPath: '/modes/'
      preLoaderRoute: typeof ModesIndexRouteImport
      parentRoute: typeof ModesRoute
    }
    '/modes/$mode': {
      id: '/modes/$mode'
      path: '/$mode'
      fullPath: '/modes/$mode'
      preLoaderRoute: typeof ModesModeRouteImport
      parentRoute: typeof ModesRoute
    }
  }
}

interface ModesRouteChildren {
  ModesModeRoute: typeof ModesModeRoute
  ModesIndexRoute: typeof ModesIndexRoute
}

const ModesRouteChildren: ModesRouteChildren = {
  ModesModeRoute: ModesModeRoute,
  ModesIndexRoute: ModesIndexRoute,
}

const ModesRouteWithChildren = ModesRoute._addFileChildren(ModesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ModesRoute: ModesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
